name: Build

on: [push, pull_request]

jobs:
  build-slides:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v4

    - name: install dependencies
      run: |
        # use ppa to get inkscape >= 1.0
        sudo add-apt-repository ppa:inkscape.dev/stable
        sudo apt-get update -q
        sudo apt-get install -y inkscape dbus-x11
        inkscape --version

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install TeXLive
      run: |
        pip install 'pygments>=2.4' 'install_texlive>=0.3.7'
        install_texlive -p $HOME/texlive -t 2024 --collections="-a" -f tex-packages.txt --update
        echo "$HOME/texlive/2024/bin/x86_64-linux" >> $GITHUB_PATH

        # make sure we can use the fonts we installed with latex also with inkscape
        mkdir -p $HOME/.local/share/fonts
        ln -s $HOME/texlive/2024/texmf-dist/fonts/opentype $HOME/.local/share/fonts
        ln -s $HOME/texlive/2024/texmf-dist/fonts/truetype $HOME/.local/share/fonts
        fc-cache
        fc-list 'Roboto'

    - name: Build logos
      run: |
        dbus-run-session make -C logos

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          logos/build/*.png
          logos/build/*.svg
          logos/build/*.pdf
          logos/build/pep-logos.zip
