name: Build

on: [push, pull_request]

jobs:
  build-slides:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y inkscape dbus-x11
        inkscape --version

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install TeXLive
      run: |
        pip install 'pygments>=2.4' https://github.com/maxnoe/texlive-batch-installation/archive/refs/tags/v0.3.0.tar.gz
        install_texlive -p $HOME/texlive -t 2021 --collections="-a" --package-file /tex-packages.txt --update
        echo "$HOME/texlive/2021/bin/x86_64-linux" >> $GITHUB_PATH

        # make sure we can use the fonts we installed with latex also with inkscape
        mkdir -p $HOME/.local/share/fonts
        ln -s $HOME/.local/texlive/2019/texmf-dist/fonts/opentype $HOME/.local/share/fonts
        ln -s $HOME/.local/texlive/2019/texmf-dist/fonts/truetype $HOME/.local/share/fonts
        fc-cache
        fc-list 'Roboto'

    - name: Build logos
      run: |
        dbus-run-session make -C logos

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          logos/build/*.png
          logos/build/*.svg
          logos/build/*.pdf
          logos/build/pep-logos.zip
